# Generated by Django 6.0 on 2026-01-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SheetUploadLog',
        ),
    ]
